server:
  port: 8888

spring:
  profiles:
    active: db
  jackson:
    # 该配置是用于解决jackson对于时间格式的配置
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # redis连接配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: #密码
    database: 0 #指定数据库 默认0
    ssl: false  #是否使用ssl连接， 默认false
    timeout: 2000 # 连接超时时间， 单位毫秒 默认0

logging:
  #  此配置是用于打印log日志所使用
  config: classpath:logback-spring.xml
  #  此配置是用与打印sql请求日志的
  level:
    demo: debug